/** Flat field labels per settings area section (from product settings map). */
export const SETTINGS_SECTION_FIELD_OUTLINES: Record<string, Record<string, string[]>> = {
  "channels-email": {
    provider: ["Amazon SES", "SendGrid", "Postmark"],
    "sending-domains": ["Add Domain", "Domain Verification", "SPF", "DKIM", "DMARC"],
    "sender-identities": ["From Name", "From Email", "Reply-To"],
    tracking: ["Open Tracking", "Click Tracking", "UTM Tracking", "Link Tracking"],
    compliance: ["Unsubscribe", "Suppression", "Preference Center", "Consent"],
  },
  "channels-push": {
    platforms: ["Android", "iOS", "Web"],
    applications: ["Add Application", "Android App", "iOS App", "Web App"],
    providers: ["Firebase FCM", "Apple APNs"],
    "device-tokens": ["Token Management", "Active Devices", "Invalid Tokens"],
    tracking: ["Sent", "Delivered", "Opened", "Clicked"],
    settings: ["Badge", "Sound", "Deep Link", "Consent"],
  },
  "channels-whatsapp": {
    "meta-connection": ["Connect Account", "Business Account", "Connection Status"],
    "phone-numbers": ["Add Number", "Verify Number", "Default Number"],
    "message-templates": ["Templates", "Create Template", "Template Status", "Template Approval"],
    media: ["Images", "Videos", "Documents", "Media Limits"],
    consent: ["Opt-In", "Opt-Out", "Consent Records", "Blocked Contacts"],
    tracking: ["Sent", "Delivered", "Read", "Replied", "Failed"],
  },
  "channels-in-app": {
    sdk: ["Web SDK", "Android SDK", "iOS SDK", "Flutter SDK"],
    applications: ["Web Apps", "Mobile Apps", "Application Keys"],
    display: ["Modal", "Banner", "Full Screen", "Custom"],
    behavior: ["Trigger Events", "Frequency Capping", "Display Duration", "Dismiss Behavior"],
    tracking: ["Viewed", "Clicked", "Dismissed", "Converted"],
  },
  "channels-content-cards": {
    sdk: ["Web SDK", "Android SDK", "iOS SDK", "Flutter SDK"],
    applications: ["Web Apps", "Mobile Apps"],
    feed: ["Default Feed", "Feed Position", "Card Expiration", "Empty State"],
    display: ["Card Layout", "Image", "Title", "Description", "CTA", "Deep Link"],
    tracking: ["Viewed", "Clicked", "Dismissed", "Converted"],
  },
  "domains-sending": {
    "sending-domains": ["Email Domains", "Tracking Domains", "Domain Verification"],
    dns: ["SPF", "DKIM", "DMARC", "DNS Status"],
    "sender-identities": ["Sender Name", "Sender Email", "Reply-To"],
    "link-tracking": ["Tracking Domain", "UTM Parameters", "Redirect Settings"],
  },
  "audience-consent": {
    "consent-management": ["Email", "Push", "WhatsApp", "In-App", "Content Cards"],
    "subscription-types": ["Marketing", "Transactional", "Promotional", "System"],
    "preference-center": ["Email Preferences", "Push Preferences", "WhatsApp Preferences", "Global Preferences"],
    suppression: ["Suppressed Emails", "Suppressed Phones", "Suppression Rules"],
    "consent-logs": ["Opt-In History", "Opt-Out History", "Consent Changes"],
  },
  "tracking-data": {
    sdk: ["Web SDK", "Android SDK", "iOS SDK", "Flutter SDK"],
    identity: ["Visitor ID", "User ID", "Anonymous Users", "Identity Resolution"],
    events: ["Standard Events", "Custom Events", "Event Properties", "Event Validation"],
    "user-attributes": ["Default Attributes", "Custom Attributes", "Attribute Types"],
    sessions: ["Session Timeout", "Session Tracking"],
    "page-views": ["Page Tracking", "URL Tracking"],
    "data-retention": ["Event Retention", "Profile Retention", "Delete Data"],
  },
  templates: {
    "email-templates": ["Templates", "Drafts", "Published", "Archived"],
    "push-templates": ["Templates", "Drafts", "Archived"],
    "whatsapp-templates": ["Templates", "Pending Approval", "Approved", "Rejected"],
    "in-app-templates": ["Modal", "Banner", "Full Screen"],
    "content-card-templates": ["Standard", "Image Card", "Custom"],
  },
  integrations: {
    messaging: ["Amazon SES", "SendGrid", "Postmark", "Firebase", "Meta WhatsApp"],
    crm: ["HubSpot", "Salesforce"],
    analytics: ["Google Analytics", "Mixpanel", "Segment"],
    data: ["Data Warehouse", "BigQuery", "S3"],
    "connected-apps": ["Active", "Available", "Disconnected"],
  },
  webhooks: {
    endpoints: ["Add Endpoint", "Active Endpoints", "Disabled Endpoints"],
    events: ["User Events", "Campaign Events", "Message Events", "System Events"],
    security: ["Webhook Secret", "Signature Verification"],
    "delivery-logs": ["Successful", "Failed", "Retry", "Response Logs"],
  },
  notifications: {
    "campaign-notifications": ["Campaign Completed", "Campaign Failed", "Campaign Paused"],
    "system-notifications": ["System Errors", "Integration Errors", "Service Status"],
    "usage-notifications": ["Usage Threshold", "Limit Reached", "Billing Alerts"],
    "security-notifications": ["New Login", "Password Change", "API Key Changes"],
  },
  security: {
    "account-security": ["Password", "Two-Factor Authentication", "Active Sessions", "Login History"],
    "api-security": ["API Keys", "Key Rotation", "Key Permissions"],
    "access-control": ["IP Restrictions", "Allowed Domains", "Session Policy"],
    "audit-logs": ["User Activity", "Configuration Changes", "Security Events", "API Activity"],
  },
  "billing-usage": {
    plan: ["Current Plan", "Upgrade", "Downgrade"],
    usage: ["Email", "Push", "WhatsApp", "In-App", "Content Cards"],
    limits: ["Contacts", "Emails", "Events", "API Requests"],
    billing: ["Payment Method", "Billing Information", "Invoices"],
    "usage-history": ["Monthly Usage", "Usage Reports"],
  },
  "developer-api": {
    api: ["API Keys", "API Documentation", "API Versions", "Rate Limits"],
    sdk: ["Web", "Android", "iOS", "Flutter"],
    "events-api": ["Track Event", "Identify User", "Track Page View"],
    "user-api": ["Create User", "Update User", "Delete User", "User Lookup"],
    "developer-tools": ["API Logs", "Event Debugger", "SDK Debugger", "Test Events"],
  },
};
